### PR TITLE
Additions of French translation

### PR DESCRIPTION
**Pull request by jbidoret**
Hi Sebastian, 
Thanks a lot for your plugin.
I added some French translations that you might consider merging into your repo.

### CODE REVIEW

**Review by sebastiangreger — APPROVED** [review]

**Comment by sebastiangreger** [comment]
Merci beaucoup pour la contribution! J'ajoute les textes a la prochaine release.

**Comment by sebastiangreger** [comment]
...and it's live: https://github.com/sebastiangreger/kirby3-commentions/releases/tag/v1.0.4

**Comment by jbidoret** [comment]
Great! Merci.

**Comment by sebastiangreger** [comment]
@jbidoret I hope you don't mind me pinging you here in a slightly off-topic manner, but I'd like to draw your attention to my update that I am no longer able to maintain the Commentions plugin in the future [→ details here](https://github.com/sebastiangreger/kirby3-commentions/issues/151).

**Pull request merged**
