### PR TITLE
Feature/anchor redirect

### PR DESCRIPTION
**Pull request by fabianmichael**
Added an anchor, so the page scrolls to the "Thank you!"-message after submitting a comment.

### CODE REVIEW

**Review by sebastiangreger — COMMENTED** [review]
This can be a valuable addition! I'm just wondering, should it be optional?

I, for my part, like to integrate the commentions-feedback block right below a header/navigation where it is visible immediately and would prefer for the browser to not "jump down" to that element (to maintain the context of the main navigation element).

What do you think?

**Comment by fabianmichael** [comment]
@sebastiangreger Just posted a test comment on your site, to understand better, what you mean. Your setup is quite a bit nicer than mine with that message appearing on top of the page, but I would categorize it as "customized commentions experience" (because everything is called "experience" nowadays). ;-)

I think it would be best to have that anchor-jumping experience enabled by default, since it plays nicer with the default implementation of the form. But there should definitely some way of disabling it.

**Comment by sebastiangreger** [comment]
> I think it would be best to have that anchor-jumping experience enabled by default, since it plays nicer with the default implementation of the form. But there should definitely some way of disabling it.

I agree. The default should be the jump.

But I for example would prefer to disable it; question is: do we increase complexity by introducing yet another config option or is the way to go that people who don't want the jump have to clone the commentions-feedback snippet and create their own (thinking of the jump-less experience™ as a customized implementation, hence custom copy of the snippet could be considered appropriate). I'm just a bit wary of adding more and more config variables, as the plugin is already laden with those ;-)

**Comment by fabianmichael** [comment]
@sebastiangreger I agreee with you … we shouldn’t make it more complicated. I got around the problem within 2 minutes by using the following JS instead:

```html
<script>
window.addEventListener("load", () => {
  const feedbackEL = document.querySelector('.commentions-feedback');
  feedbackEL.scrollIntoView({ behavior: "smooth" })
});
</script>
```
Although I would prefer the non-JS way, I think its not worth to increase complexity just for that.

**Comment by sebastiangreger** [comment]
Digging out this old PR for a quick comment: this is now configurable in v2.0: the new `$attrs` attribute of the helper snippets allows to modify the "jumping behaviour" after submission. We can add an `id` attribute to any of the three helper sections and the `jump` (or even `jump-success` and `jump-error`) attribute of the `<?commentions('form', $attrs) ?>` call then takes the user to the desired anchor (which can of course also be any other ID, not just the ones added to one of the helpers).

**Pull request closed without merging**
