### PR TITLE
Privacy by default

### PR DESCRIPTION
**Pull request by sebastiangreger**
I was experimenting with using Commentions in the most data-minimalist way possible and ran into a requirement to minimize the stored webmention data. If my only goal is to show a list of URLs that have liked/mentioned/replied a page, there is no need to store names, avatars, etc.

Documentation here: https://github.com/sebastiangreger/kirby3-commentions/tree/privacy-by-default#limiting-stored-data-fields

I slightly changed the way the `sgkirby.commentions.formfields` option - now `sgkirby.commentions.commentfields` - works: it's no longer just an array of allowed field names, but also includes a boolean to select between required and optional fields. I'm not 100% happy with the design of this array (the `true` and `false` could be misread for "use this field" and "don't use this field", while they refer to "required=true"). Happy for any suggestion how to improve this :slightly_smiling_face: 

The new `sgkirby.commentions.webmentionfields` array works in the same way: if it exists, only the fields listed in it are stored. For example using `'sgkirby.commentions.webmentionfields' => [],` discards any webmention data apart from type and source URL - enabling the solution I was aiming for.

Personally, I'd actually have a use case for even more granular control - storing names and HTML for some templates, but only the URL for others. Still thinking about how to achieve this without growing the config options too complex. Thinking of some kind of callback option or a hook instead as it's really a very extreme edge case.

### CODE REVIEW

**Comment by fabianmichael** [comment]
> I slightly changed the way the sgkirby.commentions.formfields option - now sgkirby.commentions.commentfields - works: it's no longer just an array of allowed field names, but also includes a boolean to select between required and optional fields. I'm not 100% happy with the design of this array (the true and false could be misread for "use this field" and "don't use this field", while they refer to "required=true"). Happy for any suggestion how to improve this 🙂

Agreed, that it’s not ideal. Maybe we could tune the array format a bit? 2 suggestions below:

**Option 1:** Only use a boolean value, for required fields. This is a bit more work to parse, but that could maybe all be handled by a helper function:

```php
'sgkirby.commentions.formfields' => [
  'name',
  'website' => true,
  'email' => true,
],
```

**Option 2:** Add an asterix to required fields to match the usual visual representation of required fields in forms. This is also a bit harder to parse, but not too hard in the end:

```php
'sgkirby.commentions.formfields' => [
  'name',
  'website*',
  'email*',
],
```

> Personally, I'd actually have a use case for even more granular control - storing names and HTML for some templates, but only the URL for others. Still thinking about how to achieve this without growing the config options too complex. Thinking of some kind of callback option or a hook instead as it's really a very extreme edge case.

A callback sounds like a good idea. I don't think, that anythings speaks against allowing either a function to be specified for `sgkirby.commentions.formfields` (woudl allow granular control for every single form on the site or alternatively a hook, that’s invoked before saving a commention and that can strip out unwanted data.

What do you think?

**Comment by sebastiangreger** [comment]
> **Option 1:** Only use a boolean value, for required fields. This is a bit more work to parse, but that could maybe all be handled by a helper function:

I like the simplicity and logic of this one. Implemented in 7854ed1 (I'll still clean this up eventually, using a helper function, to take the increased complexity out of the snippet).

> A callback sounds like a good idea. I don't think, that anythings speaks against allowing either a function to be specified for sgkirby.commentions.formfields (woudl allow granular control for every single form on the site

This! Instead of creating hugely complicated settings arrays for edge cases, a callback would give almost unlimited means for highly specialized solutions. I have a code snippet somewhere from another project.

> or alternatively a hook, that’s invoked before saving a commention and that can strip out unwanted data.

As far as I understood [hooks can't return anything](https://getkirby.com/docs/reference/plugins/hooks#details)? That means, an `:after` hook would be the only way to modify a specific submission. In that case, the data would already be "processed" (first stored, to then be deleted using a hook) vs. not even accepting a field; which has GDPR implications, if being super strict. Just asking, since a hook would of course be the more "stylish" way in a Kirby context compared to a function callback (basically emulating a ":before hook" with a return value) - so wouldn't want to discard this too easily...

**Comment by fabianmichael** [comment]
@sebastiangreger Though a hook cannot return anything, it might be possible to pass an object or array by reference. In that case, the hook wouldn’t need to return anything, but could still modify incoming data.

**Comment by sebastiangreger** [comment]
@fabianmichael Great, I'll look into that (this possibility didn't occur to me earlier). So a `:before` hook could be handed the submitted data as a reference, and modify it before it is processed further...

**Comment by sebastiangreger** [comment]
I couldn't get the :before hook to work with variables as reference ([$kirby->trigger()](https://getkirby.com/docs/reference/objects/kirby/trigger) does not accept attributes by reference, as far as I can tell), but the callback is very simple and works great:

```php
'sgkirby.commentions.commentfields' => function($targetPage){
  // comment forms on event pages require both name and email
  if ($targetPage->intendedTemplate()->name() === 'event') {
    return [
      'name' => true,
      'email' => true,
    ];
  }
  // on all other pages, only show optional name field
  return [
    'name',
  ];
},
```

The updated Readme chapter with a code example is [here](https://github.com/sebastiangreger/kirby3-commentions/tree/d7e63fe8f4d29b6c2237ed3e9568983116f2beb0#comment-fields) - this is much more straightforward now.

**Pull request merged**
